## 1. Thông tin tệp dữ liệu




* **Tổng số bản ghi:** 100918 bản ghi
  
* **Bảng mã (Encoding):** UTF-8

Dưới đây là bảng chi tiết về các thuộc tính (features) có trong tệp dữ liệu:

| STT | Tên cột (Column Name) | Kiểu dữ liệu (Data Type) | Ý nghĩa / Định nghĩa (Description) | Ví dụ minh họa (Example) |
| :--- | :--- | :--- | :--- | :--- |
| 1 | `sender_name` | String / Object | Tên của người gửi tin nhắn. | `Bill	` |
| 2 | `message` | String / Object | Nội dung chi tiết của tin nhắn. | `SOLD ORDER \n7010/1R PURPLE\nNEW 2026​‍‌⁠​‍​​​‍‌​​⁠⁠‍‍⁠⁠‌​‌‌‌‍‌` |
| 3 | `msg_time` | Datetime | Ngày và giờ gửi tin nhắn (Định dạng: `YYYY-MM-DD HH:MM:SS`). | `2026-06-18 03:26:00.000` |

---

In [59]:
#import library
import pandas as pd
from pathlib import Path
import re

In [61]:
file_path = Path("messages.csv")

df = pd.read_csv(
    file_path,
    engine="python",
    on_bad_lines="warn"
)

In [62]:
# display full text
pd.set_option("display.max_colwidth", None)  
pd.set_option("display.max_rows", None)      
pd.set_option("display.max_columns", None)  
pd.set_option("display.width", None)

In [65]:
df.head(5)

,sender_name,message,msg_time
0,85293522736,26240st green N2\n495000hkd,2026-06-16 00:00:02.000
1,Nacho,"You’ve tried WhatsApp groups, many platforms but found no good deals?❌\n\nThen you can simply try my platform for free.💪\n\n🔵 Join us for:\n✅ 4,000+ groups in one platform, real time WTS + WTB flow (always updated)\n✅ Auto-posting tools\n✅ Viewing dealer profile \n✅ Smart filters: price, condition, country, date",2026-06-16 00:00:02.000
2,Daniel,"\n You’ve tried WhatsApp groups, many platforms but found no good deals?❌\n\n Then you can simply try my platform for free.💪\n\n 🔵 Join us for:\n ✅ 4,000+ groups in one platform, real time WTS + WTB flow (always updated)\n ✅ Auto-posting tools\n ✅ Viewing dealer profile \n ✅ Smart filters: price, condition, country, date\n",2026-06-16 00:00:02.000
3,15162814068,"126333 Datejust 41\nWatch and Card\nSilver Dial\nTTY Jubilee Bracelet\n$14,950 + label 🏷️ \n\nCall me if I don't respond*",2026-06-16 00:00:04.000
4,Annie,Cartiers 🐆 \n\nWspn0013 6/2026 hkr 39500 -7%\nWspn0015 6/2026 hkr 46800 -9%\n\nW2sa0033 5/2026 hkr 85500 -13%\nW2sa0034 5/2026 hkr 77500 -14%\nW2sa0038 5/2026 hkr 49900 -14%\n\nWssa0018 6/2026 hkr 68500 -11%\nWssa0032 6/2026 hkr 58500 -12%\nWssa0039 5/2026 hkr 73500 -11%\nWssa0061 5/2026 hkr 63000 -10%\nWssa0062 5/2026 hkr 68500 -12%\nWssa0082 5/2026 hkr 51000 -12%\nWssa0085 5/2026 hkr 39100 -11%\nWssa0086 5/2026 hkr 35400 -13%\nWssa0096 4/2026 hkr 68500 -13%\n\nWsta0141 5/2026 hkr 42200 -10%\n\nWgba0079 5/2026 hkr 130000 -18%\n\nWjpn0087 5/2026 hkr 249000 -20%\n\nWgta0352 5/2026 hkr 69000 -20%\n\nWhsa0030 5/2026 hkr 331000 -26%,2026-06-16 00:00:04.000

In [67]:
# filter duplicate
df_unique = df.drop_duplicates(subset=["message"])

In [69]:
# keep only message field
df_message_only = df_unique[["message"]]

df_message_only.head()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            message
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       26240st green N2\n495000hkd
1                                                                                                                                                                                                                                                                                                                                         You’ve tried WhatsApp groups, many platforms but found no good deals?❌\n\nThen you can simply try my platform for free.💪\n\n🔵 Join us for:\n✅ 4,000+ groups in one platform, real time WTS + WTB flow (always updated)\n✅ Auto-posting tools\n✅ Viewing dealer profile \n✅ Smart filters: price, condition, country, date
2                                                                                                                                                                                                                                                                                                       \n    You’ve tried WhatsApp groups, many platforms but found no good deals?❌\n\n    Then you can simply try my platform for free.💪\n\n    🔵 Join us for:\n    ✅ 4,000+ groups in one platform, real time WTS + WTB flow (always updated)\n    ✅ Auto-posting tools\n    ✅ Viewing dealer profile \n    ✅ Smart filters: price, condition, country, date\n
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         126333 Datejust 41\nWatch and Card\nSilver Dial\nTTY Jubilee Bracelet\n$14,950 + label 🏷️ \n\nCall me if I don't respond*
4  Cartiers 🐆 \n\nWspn0013 6/2026 hkr 39500 -7%\nWspn0015 6/2026 hkr 46800 -9%\n\nW2sa0033 5/2026 hkr 85500 -13%\nW2sa0034 5/2026 hkr 77500 -14%\nW2sa0038 5/2026 hkr 49900 -14%\n\nWssa0018 6/2026 hkr 68500 -11%\nWssa0032 6/2026 hkr 58500 -12%\nWssa0039 5/2026 hkr 73500 -11%\nWssa0061 5/2026 hkr 63000 -10%\nWssa0062 5/2026  hkr 68500 -12%\nWssa0082 5/2026 hkr 51000 -12%\nWssa0085 5/2026 hkr 39100 -11%\nWssa0086 5/2026  hkr 35400 -13%\nWssa0096 4/2026 hkr 68500 -13%\n\nWsta0141 5/2026 hkr 42200 -10%\n\nWgba0079 5/2026  hkr 130000 -18%\n\nWjpn0087 5/2026  hkr 249000 -20%\n\nWgta0352 5/2026 hkr 69000 -20%\n\nWhsa0030 5/2026 hkr 331000 -26%

# 1. Lọc data rác dựa trên đặc điểm tệp dữ liệu

**Nhận xét**:
- Do data nằm trong group Whatsapp nên nó rất bẩn

- Rất khó để có một rule thỏa mãn mọi trường hợp, dùng rule chặt thì sẽ lọc nhầm data thật nhiều, dùng rule lỏng thì sẽ lọc được ít data rác

- Việc xây dựng một luật đáp ứng cho từng mã đồng hồ cũng không khả thi
  
- Giải pháp được đưa ra là lọc dựa trên đặc điểm tập dữ liệu: tin nhắn có giá nhiều khả năng là tin đăng bán đồng hồ, tin mua thì có các từ khóa như Want to buy, Looking for)

In [111]:
df_clone2 = df_message_only.copy()

In [113]:
# tin nhắn có giá nhiều khả năng là tin đăng bán đồng hồ

PRICE_PATTERN = re.compile(
    r"""
    (?:
        # branch 1: currency symbol before number
        (?:USD|USDT|HKD|SGD|EUR|AED|CNY|CHF|GBP|JPY|THB|INR|KRW|RMB|dhs|[\$€£¥₩₹₫₽₺₴₦฿₱₲₡₸₼₾₪₨₭₮])\s*\d+(?:[.,]\d+)*\s*[KM]?\b
        |
        # branch 2: currency symbol after number
        \b\d+(?:[.,]\d+)*\s*[KM]?\s*(?:USD|USDT|HKD|SGD|EUR|AED|CNY|CHF|GBP|JPY|THB|INR|KRW|RMB|[\$€£¥₩₹₫₽₺₴₦฿₱₲₡₸₼₾₪₨₭₮])\b
        |
        # branch 3: don't have currency symbol 295k, 143M
        \b\d+(?:[.,]\d+)*\s*[KM]\b
        |
        # branch 4: 1500000
        (?<![-./A-Z0-9])\b\d{1,3}(?:[.,]\d{3})+\b(?![-./A-Z0-9])
        |
        (?<![-./A-Z0-9])\b\d{5,6}\b(?![-./A-Z0-9])
        |
         # emoji price
        (?:[0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣]){3,}
    )
    """, 
    re.IGNORECASE | re.VERBOSE
)

In [115]:
# tin nhắn có looking for, need nhiều khả năng là tin tìm mua đồng hồ

TRADE_KEYWORDS_PATTERN = re.compile(
    r"""
    \b(?:
        WTB|BUY|WANTED|ISO|LF|NEED|ORDER|LTB|ORDER|CONFIRM|LOOKING
        SOLD\s+ORDER|             
        NEED\s+TO\s+QUOTE|NTQ|  
        WANT\s+TO\s+BUY|          
        LOOKING\s+FOR|             
        LOOKING|CONFIRM\s+ORDERS?
    )\b
    """,
    re.IGNORECASE | re.VERBOSE
)

In [117]:
def has_extra_content(text):
    cleaned = TRADE_KEYWORDS_PATTERN.sub("", text).strip(" -:,.!?") # remove keyword and special character
    
    return len(cleaned) > 3 # NEED RM -> RM

In [125]:
def check_message(message): 
    text = str(message)
    
    has_price = bool(PRICE_PATTERN.search(text))
    has_keyword = bool(TRADE_KEYWORDS_PATTERN.search(text))
    
    if has_price and len(text) > 13: # 13 là độ dài tin đăng bán ngắn nhất thu được
        return True
        
    if has_keyword:
        return has_extra_content(text)
        
    return False

In [128]:
def extract_matches(message):
  
    text = str(message)
    matches = [m.group().strip() for m in PRICE_PATTERN.finditer(text)]
    matches += [m.group().strip() for m in TRADE_KEYWORDS_PATTERN.finditer(text)]
    return list(dict.fromkeys(matches))

df_message_only["extracted_features"] = df_message_only["message"].apply(extract_matches)
df_message_only["keep"] = df_message_only["message"].apply(check_message)

df_garbage = df_message_only[~df_message_only["keep"]].copy() # chứa rác, keep là false
df_clean = df_message_only[df_message_only["keep"]].copy() # chứa message clean

In [134]:
print("Tổng số tin nhắn duy nhất:", len(df_message_only))
print("Số tin ĐƯỢC GIỮ:", len(df_clean))
print("Số tin BỊ LOẠI (Tin rác/Xã giao):", len(df_garbage))

Tổng số tin nhắn duy nhất: 100918
Số tin ĐƯỢC GIỮ: 93716
Số tin BỊ LOẠI (Tin rác/Xã giao): 7202

In [130]:
df_garbage.to_csv("garbage_message.csv", index=False)
df_clean.to_csv("clean_message.csv", index=True)